# Generated by Django 6.0.6 on 2026-06-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_stock_alter_product_image_cart_cartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('jewelery', 'Jewelery'), ("men's clothing", "Men's Clothing"), ("women's clothing", "Women's Clothing"), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('footwear', 'Footwear'), ('kitchen', 'Kitchen'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
